import "./globals.css";
import SmoothScroll from "./components/global/SmoothScroll";

export const metadata = {
  title: "Made by Sang",
  description: "Generated by create next app",
  icon: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
