import "./globals.css";
import { createClient } from "@/prismicio";
import SmoothScroll from "./components/global/SmoothScroll";
import Navbar from "./components/global/Navbar";

export const metadata = {
  title: "Made by Sang",
  description: "Generated by create next app",
  icon: {
    icon: "/favicon.jpg",
  },
};

export default async function RootLayout({ children }) {
  const client = createClient();
  const navbar = await client.getSingle("navbar");

  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          <Navbar data={navbar.data} />
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
